// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMo8H92ITN0s-amWvszT4xQhZ2FxI4BM',
    appId: '1:355481512820:web:b45c97230cb6b4bcda5a21',
    messagingSenderId: '355481512820',
    projectId: 'graduation-5cb7e',
    authDomain: 'graduation-5cb7e.firebaseapp.com',
    storageBucket: 'graduation-5cb7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw9Pjx96y-HQ2fRrceFlM9j0PZGoEpqw',
    appId: '1:355481512820:android:e650d1c77e1b659ada5a21',
    messagingSenderId: '355481512820',
    projectId: 'graduation-5cb7e',
    storageBucket: 'graduation-5cb7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo07bxjWBCnKOSgvvXYC-n3-lN96D4kI0',
    appId: '1:355481512820:ios:7f319c41de71d09cda5a21',
    messagingSenderId: '355481512820',
    projectId: 'graduation-5cb7e',
    storageBucket: 'graduation-5cb7e.appspot.com',
    iosClientId: '355481512820-sasopm2dbeep7959sn2q0tu04k16omat.apps.googleusercontent.com',
    iosBundleId: 'com.example.grduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo07bxjWBCnKOSgvvXYC-n3-lN96D4kI0',
    appId: '1:355481512820:ios:7f319c41de71d09cda5a21',
    messagingSenderId: '355481512820',
    projectId: 'graduation-5cb7e',
    storageBucket: 'graduation-5cb7e.appspot.com',
    iosClientId: '355481512820-sasopm2dbeep7959sn2q0tu04k16omat.apps.googleusercontent.com',
    iosBundleId: 'com.example.grduation',
  );
}
